from __future__ import annotations
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from config import get_settings

logger = logging.getLogger(__name__)

FLUENT_AI_SECTION = "## FluentAI Personal Notes"


class VaultWriter:
    """Writes session artifacts into an Obsidian vault.

    Portable: the vault location comes from ``settings.vault_root``. When that
    setting is empty (the default), the writer is a no-op — nothing is written
    and no path is assumed. Set ``VAULT_ROOT`` in the environment to enable it.
    """

    def __init__(self) -> None:
        self._warned_disabled = False
        self._sessions_dir: Optional[Path] = None
        self._concepts_dir: Optional[Path] = None
        self._profile_file: Optional[Path] = None

    def _resolve_root(self) -> Optional[Path]:
        root = get_settings().vault_root
        if not root:
            if not self._warned_disabled:
                logger.debug("vault_root not configured — VaultWriter is disabled (no-op)")
                self._warned_disabled = True
            return None
        return Path(root)

    def write_session(self, session_date: datetime, reflection_data: dict, transcript: str):
        """Entry point — writes all vault artifacts from a completed session."""
        root = self._resolve_root()
        if root is None:
            return  # vault integration disabled

        self._sessions_dir = root / "sessions"
        self._concepts_dir = root / "concepts"
        self._profile_file = root / "Profile (About Me).md"

        try:
            session_title = reflection_data.get("session_title", "Untitled Session")
            date_str = session_date.strftime("%Y-%m-%d")
            note_filename = f"{date_str} - {self._slugify(session_title)}.md"

            self._write_session_note(note_filename, date_str, session_title, reflection_data)
            self._update_topic_notes(date_str, note_filename, session_title, reflection_data)
            self._update_profile(date_str, reflection_data)

            logger.info(f"Vault updated: session={note_filename}")
        except Exception as e:
            logger.error(f"Vault write failed: {e}")

    def _write_session_note(
        self,
        filename: str,
        date_str: str,
        title: str,
        r: dict,
    ):
        """Write the session summary note to sessions/."""
        assert self._sessions_dir is not None
        self._sessions_dir.mkdir(parents=True, exist_ok=True)

        fluency = r.get("fluency_score", "—")
        topics = r.get("topics_discussed", [])
        went_well = r.get("went_well", [])
        mistakes = r.get("recurring_mistakes", [])
        vocab = r.get("vocab_to_learn", [])
        encouragement = r.get("encouragement", "")

        topic_links = " ".join(f"[[{t}]]" for t in topics) if topics else "—"

        lines = [
            "---",
            f"tags: [fluent-ai, english-session]",
            f"date: {date_str}",
            f"fluency_score: {fluency}",
            "---",
            "",
            f"# {title}",
            "",
            f"**Date:** {date_str}  ",
            f"**Fluency Score:** {fluency}/10  ",
            f"**Topics:** {topic_links}",
            "",
        ]

        if went_well:
            lines += ["## What You Did Well", ""]
            for item in went_well:
                lines.append(f"- {item}")
            lines.append("")

        if mistakes:
            lines += ["## Patterns to Improve", ""]
            for m in mistakes:
                pattern = m.get("pattern", "")
                example = m.get("example", "")
                better = m.get("better", "")
                lines.append(f"- **{pattern}**")
                if example:
                    lines.append(f'  - Said: *"{example}"*')
                if better:
                    lines.append(f'  - Better: *"{better}"*')
            lines.append("")

        if vocab:
            lines += ["## Vocabulary to Learn", ""]
            for v in vocab:
                word = v.get("word", "")
                meaning = v.get("meaning", "")
                example = v.get("example", "")
                lines.append(f"- **{word}** — {meaning}")
                if example:
                    lines.append(f'  - *"{example}"*')
            lines.append("")

        if encouragement:
            lines += ["## Note to Self", "", f"> {encouragement}", ""]

        lines += ["---", "*Generated by FluentAI*"]

        (self._sessions_dir / filename).write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Session note written: sessions/{filename}")

    def _update_topic_notes(
        self,
        date_str: str,
        session_filename: str,
        session_title: str,
        r: dict,
    ):
        """Create or update a concept note for each topic discussed."""
        assert self._concepts_dir is not None
        self._concepts_dir.mkdir(parents=True, exist_ok=True)
        topics = r.get("topics_discussed", [])
        session_link = f"[[{session_filename.replace('.md', '')}]]"

        for topic in topics:
            slug = self._slugify(topic)
            note_path = self._concepts_dir / f"{slug}.md"

            if note_path.exists():
                content = note_path.read_text(encoding="utf-8")
                sessions_marker = "## Sessions"
                if sessions_marker in content:
                    content = content.replace(
                        sessions_marker,
                        f"{sessions_marker}\n- {date_str} — {session_link} ({session_title})",
                    )
                else:
                    content += f"\n\n{sessions_marker}\n- {date_str} — {session_link} ({session_title})\n"
                note_path.write_text(content, encoding="utf-8")
            else:
                lines = [
                    "---",
                    f"tags: [concept, fluent-ai]",
                    f"created: {date_str}",
                    f"last_updated: {date_str}",
                    "---",
                    "",
                    f"# {topic}",
                    "",
                    "## Notes",
                    "",
                    "## Sessions",
                    f"- {date_str} — {session_link} ({session_title})",
                    "",
                ]
                note_path.write_text("\n".join(lines), encoding="utf-8")

            logger.info(f"Concept note updated: concepts/{slug}.md")

    def _update_profile(self, date_str: str, r: dict):
        """Append new personal insights to Profile (About Me).md."""
        assert self._profile_file is not None
        insights = r.get("personal_insights", [])
        if not insights:
            return

        content = self._profile_file.read_text(encoding="utf-8") if self._profile_file.exists() else ""

        new_entries = "\n".join(f"- {i} *(from {date_str})*" for i in insights)

        if FLUENT_AI_SECTION in content:
            content = content.replace(
                FLUENT_AI_SECTION,
                f"{FLUENT_AI_SECTION}\n{new_entries}",
            )
        else:
            content += f"\n\n---\n\n{FLUENT_AI_SECTION}\n\n{new_entries}\n"

        self._profile_file.write_text(content, encoding="utf-8")
        logger.info(f"Profile updated with {len(insights)} insights")

    def _slugify(self, text: str) -> str:
        text = text.lower().strip()
        text = re.sub(r"[^\w\s-]", "", text)
        text = re.sub(r"[\s_]+", "-", text)
        return text[:60]


# Singleton
vault_writer = VaultWriter()
